# Generated by Django 5.1.3 on 2024-12-03 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_requests', '0002_leaverequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
